version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:  Build Application
          command: npm install
      - run:
          name: Run Tests
          command: npm test
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:  Build Application
          command: npm install
      - run:
          name: Run Tests
          command: npm build
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - release

